### ISSUE TITLE
Cattaz has save&export functionality?

### ISSUE THREAD

**Issue by sanzaki** [FujitsuLaboratories/cattaz#22]
Hi,

I tried to use cattaz by docker-compose. I think this is very nice tool.
I want to save&export cattaz documents as .md or .txt or something.
But now maybe cattaz does't have such a functionality.
Do you have plan to develop it? ( or already I can use it? )

**Comment by ohtake** [comment]
Hi, sanzaki

Not implemented yet. Sorry for inconvenience.
I would like to implement it after [Yjs](https://github.com/y-js/yjs) v13 provides a new persistence API.

**Comment by sanzaki** [comment]
I understand your plan.
Thanks.
