### ISSUE TITLE
Is IE11 working for cattaz?

### ISSUE THREAD

**Issue by sakaia** [FujitsuLaboratories/cattaz#9]
Is IE 11 working for cattaz?
In my environment, 
The "Loading files..." message shows continuously (never switch to normal Web UI).

**Comment by ohtake** [comment]
Thank you for reporting.

Cattaz is compatible with IE11 unless Compatibility View is enabled.
I will disable Compatibility View explicitly.

**Comment by sakaia** [comment]
Would you add following URL for further reference?

Fix site display issues with Compatibility View in Internet Explorer 11
https://support.microsoft.com/en-gb/help/17472/windows-internet-explorer-11-fix-site-display-problems-compatibility-v

**Comment by ohtake** [comment]
X-UA-Compatible meta tag was added in d8e87dbe284e02152c5a264afd6a9db4e53cd5fa.
According to the document you provided, the change will hide the Compatibility View button on Windows 7.
Windows 10 does not show the button by default.
Adding the link will be superfluous.

**Comment by sakaia** [comment]
Thank you for consideration.

I am wanted to add the URL for this github issue, just for another persons reference.
Of couse, it is helpful to add the description to the cattaz document, but I am not requested.
